#include "tjsCommHead.h"
const tjs_char* MESSAGE_RESOURCE[] = {
	TJS_W("Internal error"),
	TJS_W("Warning: "),
	TJS_W("Non-global post-! operator is used (note that the post-! operator behavior is changed on TJS2 version 2.4.1)"),
	TJS_W("Cannot convert given narrow string to wide string"),
	TJS_W("Cannot convert the variable type (%1 to %2)"),
	TJS_W("Cannot convert the variable type (%1 to Object)"),
	TJS_W("Specify an ID"),
	TJS_W("Substitution in boolean context (use form of '(A=B)!=0' to compare to zero)"),
	TJS_W("This expression cannot be used as a lvalue"),
	TJS_W("Insufficient memory"),
	TJS_W("Cannot get the value of this expression"),
	TJS_W("Accessing to null object"),
	TJS_W("Member ""%1"" does not exist"),
	TJS_W("Member does not exist"),
	TJS_W("Called method is not implemented"),
	TJS_W("Invalid argument"),
	TJS_W("Invalid argument count"),
	TJS_W("Not a function or invalid method/property type"),
	TJS_W("Specify a Dictionary object or an Array object"),
	TJS_W("Specify an Array object"),
	TJS_W("Cannot free the string memory block"),
	TJS_W("Cannot allocate the string memory block"),
	TJS_W("Cannot place ""break"" or ""continue"" here"),
	TJS_W("Cannot place ""case"" here"),
	TJS_W("Cannot place ""return"" here"),
	TJS_W("Un-terminated string/regexp/octet literal"),
	TJS_W("Cannot be parsed as a number"),
	TJS_W("Un-terminated comment"),
	TJS_W("Invalid character '%1'"),
	TJS_W("Expected %1"),
	TJS_W("Syntax error (%1)"),
	TJS_W("Error in conditional compiling expression"),
	TJS_W("Super class does not exist or cannot specify the super class"),
	TJS_W("Invalid VM code"),
	TJS_W("The value is out of the range"),
	TJS_W("Invalid operation for Read-only or Write-only property"),
	TJS_W("Invalid object context"),
	TJS_W("The object is already invalidated"),
	TJS_W("""..."" is used out of functions"),
	TJS_W("Invalid date format"),
	TJS_W("Invalid value for date/time"),
	TJS_W("Cannot convert exception because ""Exception"" does not exist"),
	TJS_W("Invalid format string"),
	TJS_W("Division by zero"),
	TJS_W("Cannot reconstruct random seeds"),
	TJS_W("ID"),
	TJS_W("[out of TJS2 script]"),
	TJS_W("Total %1 Object(s) was not freed"),
	TJS_W(" <-- "),
	TJS_W(" <-- "),
	TJS_W("Object %1 [%2] wes not freed / The object was created at : %2"),
	TJS_W("Object %1 [%2] wes not freed / The object was created at : %2"),
	TJS_W("Group by object type and location where the object was created"),
	TJS_W("Group by object type"),
	TJS_W("%1 time(s) : [%2] %3"),
	TJS_W("%1 time(s) : [%2] %3"),
	TJS_W("%1 time(s) : [%2]"),
	TJS_W("%4: Running code on deleting-in-progress object %1[%2] / The object was created at : %3"),
	TJS_W("%4: Running code on deleting-in-progress object %1[%2] / The object was created at : %3"),
	TJS_W("Write error"),
	TJS_W("Read error"),
	TJS_W("Seek error"),
	TJS_W("Bytecode read error. File is broken or it's not bytecode file."),
	TJS_W("Object Hash Map log version mismatch"),
	TJS_W("Currupted Object Hash Map log"),
	TJS_W("Unknown failure : %08X"),
	TJS_W("Unknown pack/unpack TEMPLATE charcter"),
	TJS_W("Unknown bit string charcter"),
	TJS_W("Unknown Hex string charcter"),
	TJS_W("Not supported uuencode"),
	TJS_W("Not supported BER"),
	TJS_W("Not supported unpack 'p'"),
	TJS_W("Not supported unpack 'P'"),
	TJS_W("Kirikiri Z Executable core /%1 (Compiled on %DATE% %TIME%) TJS2/%2 Copyright (C) 1997-2013 W.Dee and contributors All rights reserved."),
	TJS_W("The details of version information can be perused if -about is attached and started. "),
	TJS_W("http://krkrz.github.io/"),
	TJS_W("Internal Error: at %1 line %2"),
	TJS_W("Invalid Parameter"),
	TJS_W("Debug option enabled"),
	TJS_W("Command line parameter %1 = %2 is invalid. It's used default."),
	TJS_W("Command line parameter %1 = %2 is invalid."),
	TJS_W("Not implemented"),
	TJS_W("Cannot open storage %1"),
	TJS_W("Cannot find storage %1"),
	TJS_W("Cannot open storage %1 for writing"),
	TJS_W("Cannot find storage %1 in archive %2"),
	TJS_W("Invalid path name %1"),
	TJS_W("Not supported media type ""%1"""),
	TJS_W("Cannot unbind XP3 exe %1"),
	TJS_W("%1 is not XP3 archive or unsupported"),
	TJS_W("Use path delimiter '>' or '/'"),
	TJS_W("(Attention) Filename ""%1"" contains '#'"),
	TJS_W("Cannot get local name from %1"),
	TJS_W("Read error"),
	TJS_W("Write error"),
	TJS_W("Seek error"),
	TJS_W("Truncate error"),
	TJS_W("Cannot allocate memory"),
	TJS_W("Unpompression failed"),
	TJS_W("Compression failed"),
	TJS_W("Cannot write to archive"),
	TJS_W("%1 is unsupported cipger mode"),
	TJS_W("%1 is unsupported encoding"),
	TJS_W("%1 is unsupported mode string"),
	TJS_W("Unknown graphic format %1"),
	TJS_W("Cannot suggest graphics extension for %1"),
	TJS_W("Mask size mismath"),
	TJS_W("Province image %1 size mismatch"),
	TJS_W("Image Load Error /%1"),
	TJS_W("JPEG Read Error /%1"),
	TJS_W("PNG Read Error /%1"),
	TJS_W("ERI Read Error /%1"),
	TJS_W("TLG Read Error /%1"),
	TJS_W("Invalid image save type (%1)"),
	TJS_W("Invalid operation for 8bpp"),
	TJS_W("Invalid operation for 32bpp"),
	TJS_W("Specify Window class object"),
	TJS_W("Specify Layer class object"),
	TJS_W("Specify Layer or Bitmap class object"),
	TJS_W("Cannot accept omAuto mode"),
	TJS_W("Cannot create empty layer image"),
	TJS_W("Cannot set primary layer invisible"),
	TJS_W("Cannot move primary layer"),
	TJS_W("Cannot set parent self"),
	TJS_W("Cannot move next to self or not siblings"),
	TJS_W("Cannot move primary or siblingless"),
	TJS_W("Cannot move to under Other primary layer"),
	TJS_W("Invalid Image position"),
	TJS_W("Cannot set Mode to disabled or modal"),
	TJS_W("Not drawable layer type"),
	TJS_W("Source layer has no image"),
	TJS_W("Unsupported layer type %1"),
	TJS_W("Not drawble face type %1"),
	TJS_W("Cannot convert layer type using given direction"),
	TJS_W("Negative opacity not supported on this face"),
	TJS_W("Source rectangle out of bitmap"),
	TJS_W("Box blur area must contain center pixel"),
	TJS_W("Box blur area must be smaller than 16 million"),
	TJS_W("Cannot change focus in processing focus"),
	TJS_W("Window has no layer"),
	TJS_W("Window has already primary layer"),
	TJS_W("Specified event %1 needs parameter"),
	TJS_W("Specified event %1 needs parameter %2"),
	TJS_W("Specified event name %1 is unknown"),
	TJS_W("Out of Rectangle"),
	TJS_W("Invalid method in updating"),
	TJS_W("Cannot create instance"),
	TJS_W("Unknown wave format %1"),
	TJS_W("Current transition must be stopping"),
	TJS_W("Transition handler error %1"),
	TJS_W("Transition %1 already registerd"),
	TJS_W("Cannot find transition handler %1"),
	TJS_W("Specify transition source"),
	TJS_W("This layer cannot have image"),
	TJS_W("Transition source and destination must have image"),
	TJS_W("Cannot load rule graphics %1"),
	TJS_W("Specify option %1"),
	TJS_W("Transition layer size mismatch %1 and %2"),
	TJS_W("Transition mutual source"),
	TJS_W("Warring : Method %1 %2th parameter had is ignore. Hold destination alpha parameter is now deprecated."),
	TJS_W("Cannot connect multiple wave sound buffer at once"),
	TJS_W("Invalid window size must be in 64 to 32768"),
	TJS_W("Invalid overlap count must be in 2 to 32"),
	TJS_W("Currently async load bitmap"),
	TJS_W("copying to clipboard failed."),
	TJS_W("Invalid UTF-16 to UTF-8"),
	TJS_W("(info) Loading startup script : "),
	TJS_W("(info) Startup script ended."),
	TJS_W("sizeof(tjs_char) must be 2 or 4."),
	TJS_W("Media name ""%1"" had already been registered"),
	TJS_W("Media name ""%1"" is not registered"),
	TJS_W("(info) Rebuilding Auto Path Table ..."),
	TJS_W("(info) Total %1 file(s) found, %2 file(s) activated. (%3ms)"),
	TJS_W("Error in retrieving System.onActivate/onDeactivate : %1"),
	TJS_W("The host is not a 16-bit unicode system."),
	TJS_W("(info) Trying to read XP3 virtual file system information from : %1"),
	TJS_W("Specified storage had been protected!"),
	TJS_W("(info) Failed."),
	TJS_W("(info) Done. (contains %1 file(s), %2 segment(s))"),
	TJS_W("\r\n\r\n\r\n==============================================================================\r\n==============================================================================\r\n"),
	TJS_W("\n\n\n==============================================================================\n==============================================================================\n"),
	TJS_W("MS Sans Serif"),
	TJS_W("Can't open font file '%1$s'"),
	TJS_W("Font '%1$s' cannot be used"),
	TJS_W("Font Rasterize error."),
	TJS_W("BITFIELDS not supported."),
	TJS_W("Compressed BMP not supported."),
	TJS_W("Unsupported color mode for palettized image."),
	TJS_W("This is not a Windows BMP file or an OS/2 BMP file."),
	TJS_W("Non-supported header version."),
	TJS_W("(info) Touching "),
	TJS_W(" ... aborted [timed out]"),
	TJS_W(" ... aborted [limit bytes exceeded]"),
	TJS_W("Faild glyph for DrawGlyph."),
	TJS_W("Panic! Layer object is not properly constructed. The constructor was not called??"),
	TJS_W("Unknown update type"),
	TJS_W("Unknown transition type"),
	TJS_W("Update type of tutGiveUpdate is not yet supported"),
	TJS_W("error code : "),
	TJS_W("JPEG does not support palettized image"),
	TJS_W("libpng error."),
	TJS_W("Unsupported color type for palattized image"),
	TJS_W("Unsupported color type"),
	TJS_W("Too large image"),
	TJS_W("PNG save error."),
	TJS_W("TLG cannot be used as universal transition rule, province(_p) or mask(_m) images."),
	TJS_W("Unsupported color count : "),
	TJS_W("Data flag must be 0 (any flags are not yet supported)"),
	TJS_W("Unsupported color type : "),
	TJS_W("External golomb bit length table is not yet supported."),
	TJS_W("Unsupported entropy coding method"),
	TJS_W("Invalid TLG header or unsupported TLG version."),
	TJS_W("Malformed TLG SDS tag structure, missing colon after name length"),
	TJS_W("Malformed TLG SDS tag structure, missing equals after name"),
	TJS_W("Malformed TLG SDS tag structure, missing colon after value length"),
	TJS_W("Malformed TLG SDS tag structure, missing comma after a tag"),
	TJS_W("File size is zero."),
	TJS_W("Memory allocation error."),
	TJS_W("File read error."),
	TJS_W("Signature not found or invalid pre-rendered font file."),
	TJS_W("Not a 16-bit UNICODE font file."),
	TJS_W("Invalid header version."),
	TJS_W("SaveTLG6: Insufficient memory"),
	TJS_W("SaveTLG6: Too large bit length (given image may be too large)"),
	TJS_W("Could not retrive interface from given draw device"),
	TJS_W("Script exception raised"),
	TJS_W("Hardware exception raised"),
	TJS_W("Script Editor (Main)"),
	TJS_W("Script Editor (Exception)"),
	TJS_W("Not found krdevui.dll"),
	TJS_W("Invalid krdevui.dll"),
	TJS_W("Invalid bpp"),
	TJS_W("Cannot load Plugin %1"),
	TJS_W("Not valid plugin %1"),
	TJS_W("Faild to release plugin"),
	TJS_W("Cannot link plugin while plugin linking"),
	TJS_W("Not Susie Plugin"),
	TJS_W("Susie Plugin error : %1"),
	TJS_W("Cannot release plugin"),
	TJS_W("Not loaded plugin %1"),
	TJS_W("Cannot allocate memory for Bitmap : %1 (size=%2)"),
	TJS_W("Scan line %1 is range over (0 to %2)"),
	TJS_W("Plugin Error : %1"),
	TJS_W("Invalid CD-DA Drive"),
	TJS_W("CD-DA Drive not found"),
	TJS_W("MCI Error : %1"),
	TJS_W("Invalid SMF : %1"),
	TJS_W("Malformed MIDI Message"),
	TJS_W("DirectSound Initialize file : %1"),
	TJS_W("Cannot create DirectSound secondary buffer : %1/%2"),
	TJS_W("Invalid loop information %1"),
	TJS_W("Not child menu Item"),
	TJS_W("Cannot initialize Direct3D : %1"),
	TJS_W("Cannot find display mode : %1"),
	TJS_W("Cannot switch to fullscreen : %1"),
	TJS_W("Invalid property in fullscreen : %1"),
	TJS_W("Invalid method in fullscreen : %1"),
	TJS_W("Cannot load mouse cursor : %1"),
	TJS_W("Cannot load krmovie.dll"),
	TJS_W("Invalid krmovie.dll"),
	TJS_W("Error in krmovie.dll : %1"),
	TJS_W("Window already missing"),
	TJS_W("Prerendered font mapping failed : %1"),
	TJS_W("Cannot write %1."),
	TJS_W("Did not exit %1. Cannot delete file."),
	TJS_W("Cannot execute %1."),
	TJS_W("Plugin require %1 funcion. Bat not found function in this file."),
	TJS_W(" = (Exception)"),
	TJS_W("Console : "),
	TJS_W("(info) Listing files in %1 Åc"),
	TJS_W("(info) Total physical memory : %1"),
	TJS_W("(info) Selected project directory : %1"),
	TJS_W("too small executable size."),
	TJS_W("(info) Loading executable embedded options failed (ignoring) : %1"),
	TJS_W("(info) Loading executable embedded options succeeded."),
	TJS_W("file not found."),
	TJS_W("(info) Loading configuration file ""%1"" failed (ignoring) : %2"),
	TJS_W("(info) Loading configuration file ""%1"" succeeded."),
	TJS_W("(info) Data path does not exist, trying to make it ... %1"),
	TJS_W("ok."),
	TJS_W("failed."),
	TJS_W("(info) Data path : %1"),
	TJS_W("(info) Specified option(s) (earlier item has more priority) :"),
	TJS_W(" (none)"),
	TJS_W("(info) CPU clock (roughly) : %dMHz"),
	TJS_W("Program started on %1 (%2)"),
	TJS_W("Kirikiri"),
	TJS_W("Unknown error!"),
	TJS_W("Exit code: %d\n"),
	TJS_W("Fatal Error"),
	TJS_W("Enable Digitizer"),
	TJS_W("The device has an integrated touch digitizer. "),
	TJS_W("The device has an external touch digitizer. "),
	TJS_W("The device has an integrated pen digitizer."),
	TJS_W("The device has an external pen digitizer."),
	TJS_W("The device supports multiple sources of digitizer input. "),
	TJS_W("The device is ready to receive digitizer input."),
	TJS_W("CPU check failure."),
	TJS_W("CPU check failure: CPU family 4 or lesser is not supported\r\n%1"),
	TJS_W("(info) CPU #%1 : "),
	TJS_W("CPU check failure: Not supported CPU\r\n%1"),
	TJS_W("(info) finally detected CPU features : %1"),
	TJS_W("CPU check failure: Not supported CPU\r\n%1"),
	TJS_W("(info) CPU clock : %.1fMHz"),
	TJS_W("Layer bitmap: Buffer underrun detected. Check your drawing code!"),
	TJS_W("Layer bitmap: Buffer overrun detected. Check your drawing code!"),
	TJS_W("Faild to create Direct3D9."),
	TJS_W("Faild to decide backbuffer format."),
	TJS_W("Faild to create Direct3D9 Device."),
	TJS_W("Faild to set viewport."),
	TJS_W("Faild to set render state."),
	TJS_W("warning : Image size too large. May be cannot create texture."),
	TJS_W("Use power of two surface."),
	TJS_W("Cannot allocate D3D off-screen surface/HR=%1"),
	TJS_W("BasicDrawDevice: Failed to create Direct3D devices: %1"),
	TJS_W("BasicDrawDevice: Failed to create Direct3D devices: unknown reason"),
	TJS_W("BasicDrawDevice: Texture has already been locked (StartBitmapCompletion() has been called twice without EndBitmapCompletion()), unlocking the texture."),
	TJS_W("Internal error/HR=%1"),
	TJS_W("BasicDrawDevice: (inf) Polygon drawing failed/HR=%1"),
	TJS_W("BasicDrawDevice: (inf) IDirect3DDevice::Present failed/HR=%1"),
	TJS_W("ChangeDisplaySettings failed: DISP_CHANGE_RESTART"),
	TJS_W("ChangeDisplaySettings failed: DISP_CHANGE_BADFLAGS"),
	TJS_W("ChangeDisplaySettings failed: DISP_CHANGE_BADPARAM"),
	TJS_W("ChangeDisplaySettings failed: DISP_CHANGE_FAILED"),
	TJS_W("ChangeDisplaySettings failed: DISP_CHANGE_BADMODE"),
	TJS_W("ChangeDisplaySettings failed: DISP_CHANGE_NOTUPDATED"),
	TJS_W("ChangeDisplaySettings failed: unknown reason (%1)"),
	TJS_W("Failed to create screen DC"),
	TJS_W("Failed to create offscreen bitmap"),
	TJS_W("Failed to create offscreen DC"),
	TJS_W("(info) Susie plugin info : %1"),
	TJS_W("Non-supported bitmap header was given from susie plug-in."),
	TJS_W("BasicDrawDevice: Failed to create Direct3D Device: %1"),
	TJS_W("BasicDrawDevice: Failed to create Direct3D Device: unknown reason"),
	TJS_W("Fatal: Could not create any drawer objects."),
	TJS_W("""basic draw"" device does not support layer manager more than 1"),
	TJS_W("Invalid video size"),
	TJS_W("Rough VSync interval read from API : %1"),
	TJS_W("Rough VSync interval still seems wrong, assuming default value (16)"),
	TJS_W("(info) IDirect3D9 or higher detected. Retrieving current Direct3D driver information..."),
	TJS_W("(info) Failed."),
	TJS_W("(info) Loading Direct3D ..."),
	TJS_W("Cannot load d3d9.dll"),
	TJS_W("Missing Direct3DCreate9 in d3d9.dll"),
	TJS_W("(info) environment: using %1"),
	TJS_W("(info) Searching best fullscreen resolution ..."),
	TJS_W("(info) condition: preferred screen mode: %1"),
	TJS_W("(info) condition: mode: %1"),
	TJS_W("(info) condition: zoom mode: %1"),
	TJS_W("(info) environment: default screen mode: %1"),
	TJS_W("(info) environment: default screen aspect ratio: %1 : %2"),
	TJS_W("(info) environment: available display modes:"),
	TJS_W("(info) Panic! There is no reasonable candidate screen mode provided from the driver ... trying to use the default screen size and color depth ..."),
	TJS_W("(info) result: candidates:"),
	TJS_W("(info) Trying screen mode: %1"),
	TJS_W("All screen mode has been tested, but no modes available at all."),
	TJS_W("(info) Changing screen mode succeeded"),
	TJS_W("Select XP3 file or folder"),
	TJS_W("D3D : The device has been lost but cannot be reset at this time."),
	TJS_W("D3D : Internal driver error. Applications should destroy and recreate the device when receiving this error. "),
	TJS_W("D3D : The method call is invalid. For example, a method's parameter may not be a valid pointer."),
	TJS_W("D3D : Direct3D does not have enough display memory to perform the operation. "),
	TJS_W("D3D : Direct3D could not allocate sufficient memory to complete the call."),
	TJS_W("D3D : The pixel format of the texture surface is not valid."),
	TJS_W("D3D : The device does not support a specified texture-blending operation for color values."),
	TJS_W("D3D : The device does not support a specified texture-blending argument for color values."),
	TJS_W("D3D : The device does not support a specified texture-blending operation for the alpha channel."),
	TJS_W("D3D : The device does not support a specified texture-blending argument for the alpha channel."),
	TJS_W("D3D : The application is requesting more texture-filtering operations than the device supports."),
	TJS_W("D3D : The current texture filters cannot be used together."),
	TJS_W("D3D : The device does not support the specified texture factor value. Not used; provided only to support older drivers."),
	TJS_W("D3D : The currently set render states cannot be used together."),
	TJS_W("D3D : The device does not support the specified texture filter."),
	TJS_W("D3D : The current textures cannot be used simultaneously."),
	TJS_W("D3D : The requested item was not found."),
	TJS_W("D3D : There is more data available than the specified buffer size can hold."),
	TJS_W("D3D : The device has been lost but can be reset at this time."),
	TJS_W("D3D : This device does not support the queried technique."),
	TJS_W("D3D : The requested device type is not valid."),
	TJS_W("D3D : Not used."),
	TJS_W("D3D : The previous blit operation that is transferring information to or from this surface is incomplete."),
	TJS_W("D3D : The device that returned this code caused the hardware adapter to be reset by the OS."),
	TJS_W("D3D : The device does not support overlay for the specified size or display mode. "),
	TJS_W("D3D : The device does not support overlay for the specified surface format. "),
	TJS_W("D3D : The specified content cannot be protected."),
	TJS_W("D3D : The specified cryptographic algorithm is not supported."),
	TJS_W("D3D : The present statistics have no orderly sequence."),
	TJS_W("D3D : The hardware adapter has been removed."),
	TJS_W("D3D : This is a success code. However, the autogeneration of mipmaps is not supported for this format."),
	TJS_W("D3D : An undetermined error occurred inside the Direct3D subsystem."),
	TJS_W("D3D : An invalid parameter was passed to the returning function."),
	TJS_W("D3D : Unknown error."),
	TJS_W("Access Violation: The thread attempts to read from or write to a virtual address for which it does not have access."),
	TJS_W("Break Point: A breakpoint is encountered."),
	TJS_W("Data Type Misalignment: The thread attempts to read or write data that is misaligned on hardware that does not provide alignment. For example, 16-bit values must be aligned on 2-byte boundaries, 32-bit values on 4-byte boundaries, and so on."),
	TJS_W("Single Step: A trace trap or other single instruction mechanism signals that one instruction is executed."),
	TJS_W("Array Bounds Exceede: The thread attempts to access an array element that is out of bounds, and the underlying hardware supports bounds checking."),
	TJS_W("Denormal Operand: One of the operands in a floating point operation is denormal. A denormal value is one that is too small to represent as a standard floating point value."),
	TJS_W("Divide By Zero: The thread attempts to divide a floating point value by a floating point divisor of 0 (zero)."),
	TJS_W("Inexact Result: The result of a floating point operation cannot be represented exactly as a decimal fraction."),
	TJS_W("Invalid Operation: A floating point exception that is not included in this list."),
	TJS_W("Overflow: The exponent of a floating point operation is greater than the magnitude allowed by the corresponding type."),
	TJS_W("Stack Check: The stack has overflowed or underflowed, because of a floating point operation."),
	TJS_W("Underflow: The exponent of a floating point operation is less than the magnitude allowed by the corresponding type."),
	TJS_W("Divide By Zero: The thread attempts to divide an integer value by an integer divisor of 0 (zero)."),
	TJS_W("Overflow: The result of an integer operation creates a value that is too large to be held by the destination register. In some cases, this will result in a carry out of the most significant bit of the result. Some operations do not set the carry flag."),
	TJS_W("Priv Instruction: The thread attempts to execute an instruction with an operation that is not allowed in the current computer mode."),
	TJS_W("Noncontinuable Exception: The thread attempts to continue execution after a non-continuable exception occurs."),
	TJS_W("Guard Page: The thread accessed memory allocated with the PAGE_GUARD modifier."),
	TJS_W("Illegal Instruction: The thread tries to execute an invalid instruction."),
	TJS_W("In Page Error: The thread tries to access a page that is not present, and the system is unable to load the page. For example, this exception might occur if a network connection is lost while running a program over a network."),
	TJS_W("Invalid Disposition: An exception handler returns an invalid disposition to the exception dispatcher. Programmers using a high-level language such as C should never encounter this exception."),
	TJS_W("Invalid Handle: The thread used a handle to a kernel object that was invalid (probably because it had been closed.)"),
	TJS_W("Stack Overflow: The thread uses up its stack."),
	TJS_W("Unwind Consolidate: A frame consolidation has been executed."),
	TJS_W("Cannot Show Modal."),
	TJS_W("Cannot Show Modal. When it is single window."),
};
